-- +migrate Up
ALTER TABLE tickets
    ADD COLUMN IF NOT EXISTS batch_id VARCHAR(64) DEFAULT '',
    ADD COLUMN IF NOT EXISTS payment_method VARCHAR(20) NOT NULL DEFAULT 'gateway',
    ADD COLUMN IF NOT EXISTS payment_reference VARCHAR(128),
    ADD COLUMN IF NOT EXISTS payment_used BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS payment_status VARCHAR(20) NOT NULL DEFAULT 'pending',
    ADD COLUMN IF NOT EXISTS cancelled_at TIMESTAMP NULL;
